- name: Install nginx, sudo, cron
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - nginx
  - sudo
  - cron
  - git

- name: "Create Unix group dehydrated - users in this group have access to key-material"
  group:
    system: yes
    name: dehydrated
    state: present

- name: Create user dehydrated
  user:
    name: dehydrated
    comment: "Created by Ansible"
    group: dehydrated
    home: /usr/local/dehydrated

- name: "Add www-data to group dehydrated"
  user:
    name: www-data
    groups: dehydrated
    append: yes

- name: "Sudo: dehydrated may reload nginx"
  copy:
    src: files/sudoers
    dest: "/etc/sudoers.d/nginx-api-gateway"
    owner: root
    group: root
    mode: '0600'

- name: clone / update dehydrated from github
  become: true
  become_user: dehydrated
  become_method: sudo
  git:
    repo: https://github.com/lukas2511/dehydrated.git
    dest: /usr/local/dehydrated/lib
    clone: yes
    update: yes
    force: yes

- name: 'Create /usr/local/dehydrated/etc'
  file:
    owner: dehydrated
    group: root
    path: /usr/local/dehydrated/etc
    state: directory
    mode: '0750'

- name: 'Create /usr/local/dehydrated/www/.well-known/acme-challenge for challanges'
  file:
    owner: dehydrated
    group: www-data
    path: /usr/local/dehydrated/www/.well-known/acme-challenge
    state: directory
    recurse: yes
    mode: '0750'

- name: 'Create /usr/local/dehydrated/bin'
  file:
    owner: dehydrated
    group: dehydrated
    path: /usr/local/dehydrated/bin
    state: directory
    recurse: yes
    mode: '0750'

- file:
    owner: dehydrated
    group: root
    src: '/usr/local/dehydrated/etc'
    dest: '/etc/dehydrated'
    state: link
    force: true

- name: 'Create Configuration /usr/local/dehydrated/etc/config'
  copy:
    src: files/dehydrated.conf
    dest: "/usr/local/dehydrated/etc/config"
    owner: dehydrated
    group: root
    mode: '0640'

- name: "Register account at lets encrypt"
  command: "sudo -u dehydrated /usr/local/dehydrated/lib/dehydrated  --register --accept-terms"

- name: Register specified domains in /usr/local/dehydrated/domains.txt
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Domains from nginx-api-gateway"
    create: yes
    path: /usr/local/dehydrated/etc/domains.txt
    block: |
      {{ nginx_api_gateway.domains | join(' ') }}

- name: Create nginx http configuration
  template: >
    src=nginx.conf.j2
    dest="/etc/nginx/sites-available/nginx-api-gateway-http.conf"
    owner=root
    group=root
    mode='0600'

- name: "Link http configuration / enable"
  file:
    src: '/etc/nginx/sites-available/nginx-api-gateway-http.conf'
    dest: '/etc/nginx/sites-enabled/nginx-api-gateway-http.conf'
    state: link

- service:
    name: nginx
    state: reloaded

- name: "Copy cron batchfile"
  copy:
    src: 'files/cron.sh'
    dest: '/usr/local/dehydrated/bin/cron.sh'
    owner: dehydrated
    group: dehydrated
    mode: '0700'

- name: "Cron entry each week"
  cron:
    name: "Renew certificates"
    job: '/usr/local/dehydrated/bin/cron.sh'
    user: dehydrated
    special_time: 'weekly'

- name: "Request certificate"
  command: "sudo -u dehydrated /usr/local/dehydrated/bin/cron.sh"

- name: "Workaround: Fix Ownership of /usr/local/dehydrated"
  file:
    path: /usr/local/dehydrated
    owner: dehydrated
    group: dehydrated
    recurse: yes

- name: "Workaround: Fix Permissions of /usr/local/dehydrated/certs"
  file:
    path: /usr/local/dehydrated/certs
    owner: dehydrated
    group: dehydrated
    recurse: yes
    mode: '0750'

- name: "Create nginx TLS configuration"
  template: >
    src=nginx-ssl.conf.j2
    dest="/etc/nginx/sites-available/nginx-api-gateway-https.conf"
    owner=root
    group=root
    mode='0600'

- name: "Link http configuration / enable"
  file:
    src: '/etc/nginx/sites-available/nginx-api-gateway-https.conf'
    dest: '/etc/nginx/sites-enabled/nginx-api-gateway-https.conf'
    state: link

- service:
    name: nginx
    state: reloaded
